export { AdminProductCreatePrice } from './admin-product-create-price'
export { AdminProductCreateQuantity } from './admin-product-create-quantity'
export { AdminProductCreateName } from './admin-product-create-name'
export { AdminProductCreateCategory } from './admin-product-create-category'
export { AdminProductCreateModel } from './admin-product-create-model'
export { AdminProductCreateIsNew } from './admin-product-create-isNew'
export { AdminProductCreateDescription } from './admin-product-create-description'
export { AdminProductCreateImage } from './admin-product-create-image'

export { AdminProductCreate } from './admin-product-create'
